language: python
python:
- '2.7'
- '3.4'
- 'pypy'
env:
- CMAKE_VERSION="3.1"
- CMAKE_VERSION="2.8"
install:
- if [ ${CMAKE_VERSION} == "3.1" ]; then
     sudo apt-get -y purge cmake;
     sudo add-apt-repository -y ppa:kubuntu-ppa/beta;
     sudo apt-get update;
     sudo apt-get install cmake;
  fi
- pip install -r requirements.txt
- pip install polysquare-generic-file-linter python-coveralls flake8 pep8-naming pylint coverage
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
    pip install http://sourceforge.net/projects/pychecker/files/pychecker/0.8.19/pychecker-0.8.19.tar.gz/download;
  fi
- gem install mdl
script:
- python setup.py build
- coverage run --source=cmakeast setup.py test
- python setup.py install
- pylint -f colorized tests/ cmakeast/ --disable=r0903,R0904
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
    pychecker tests/*.py cmakeast/*.py;
  fi
- flake8 tests/ cmakeast/
- mdl .
- find cmakeast tests -type f -name "*.py" | xargs -L 1 polysquare-generic-file-linter
after_success:
- coverage report -m
- coveralls
- rm -rf polysquare_generic_file_linter.egg-info/
- rm -rf build/
deploy:
  provider: pypi
  user:
    secure: n+N1B9CiMyHM2SMdkCfRqUk7CIWYA9mtlez7lQW7iCLQNYCvEoZprvUnlvUlKUdafwBWi543Ezes+VTm3cyC9NoTL/NKfFZ4J8ZpBl4JGJJNfnKlXjBsmp2LFCySDVFwft1ed9miIjqkzsYTD2ohyBX+An70yfxMHfQ5DnS3D1Y=
  password:
    secure: i6YvJQnKlOj7kGVUwLn4gL6gYRPoX83IYusz/8GUyA8wz3p3Uiu5jtWwqpu3/U538ESfGFhbaj2bf9VtVbixpk/8+MrGYBVGM+42MB9VpLd6sADe0dqoyW2+yIgodeoLNxBKhK8wg0jVmEtSzRQuakSijlpWF+Pj9lit4GEhBcA=
  on:
    repo: polysquare/cmake-ast
    branch: master
