language: python
sudo: false
cache:
  directories:
  - ~/virtualenv
  - ~/container
python:
- '2.7'
- '3.4'
- 'pypy'
env:
- CMAKE_VERSION="latest"
- CMAKE_VERSION="3.0"
- CMAKE_VERSION="2.8"
install:
# Setup a distro container so that we can install CMake. This is used to
# run the smoke tests against a CMake installation.
#
# The initial build of the container will not contain any of our packages.
# CMake will be purged from the container and packages will be installed
# from the CMAKE_VERSION repository files. This is because caching is
# done on the basis of the python version and not the CMake version.
#
# polysquare-travis-container does not work with pypy, so we cannot do this
# on pypy.
- curl -L public-travis-scripts.polysquare.org/python-setup-with-doc.sh | bash
# Export cabal binary path so that setuptools finds it when installing
# polysquare-travis-container
- export PATH=${HOME}/.cabal/bin:${PATH}
- if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]] ; then
    export CONTAINER_DISTRO=Ubuntu;
    export CONTAINER_RELEASE=precise;
    curl -L public-travis-scripts.polysquare.org/distro-container.sh | bash;
    repo=$(cat "ci/REPOSITORIES.Ubuntu.${CMAKE_VERSION}");
    export PATH=${HOME}/container/ubuntu-core-12.04.5-core-amd64.tar.gz.root/usr/bin:${PATH};
    psq-travis-container-exec ~/container --cmd bash "${PWD}/ci/install-cmake-from-repo.sh" "${repo}";
  fi
script:
- export MODULE=cmakeast
- curl -L public-travis-scripts.polysquare.org/python-test-module.sh | bash
after_success:
- curl -L public-travis-scripts.polysquare.org/python-coverage.sh | bash
before_deploy:
- source python-prepare-doc-deploy.sh
deploy:
  provider: pypi
  user:
    secure: n+N1B9CiMyHM2SMdkCfRqUk7CIWYA9mtlez7lQW7iCLQNYCvEoZprvUnlvUlKUdafwBWi543Ezes+VTm3cyC9NoTL/NKfFZ4J8ZpBl4JGJJNfnKlXjBsmp2LFCySDVFwft1ed9miIjqkzsYTD2ohyBX+An70yfxMHfQ5DnS3D1Y=
  password:
    secure: i6YvJQnKlOj7kGVUwLn4gL6gYRPoX83IYusz/8GUyA8wz3p3Uiu5jtWwqpu3/U538ESfGFhbaj2bf9VtVbixpk/8+MrGYBVGM+42MB9VpLd6sADe0dqoyW2+yIgodeoLNxBKhK8wg0jVmEtSzRQuakSijlpWF+Pj9lit4GEhBcA=
  on:
    repo: polysquare/cmake-ast
    branch: master
