language: python
sudo: false
cache:
  directories:
  - ~/virtualenv
  - ~/container
python:
- '2.7'
- '3.4'
- 'pypy'
env:
- CMAKE_VERSION="latest"
- CMAKE_VERSION="3.0"
- CMAKE_VERSION="2.8"
install:
# Setup a distro container so that we can install CMake. This is used to
# run the smoke tests against a CMake installation.
#
# First copy the packages and repositories files to our current
# working directory from ci/DEPENDENCIES.Ubuntu.{cmake_release} and
# ci/REPOSITORIES.Ubuntu.{cmake_release}.
#
# polysquare-travis-container does not work with pypy, so we cannot do this
# on pypy.
- if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]] ; then
    export CONTAINER_DISTRO=Ubuntu;
    export CONTAINER_RELEASE=precise;
    cp "ci/REPOSITORIES.Ubuntu.${CMAKE_VERSION}" REPOSITORIES.Ubuntu;
    cp "ci/DEPENDENCIES.Ubuntu" DEPENDENCIES.Ubuntu;
    curl -L public-travis-scripts.polysquare.org/distro-container.sh | bash;
    export PATH=${HOME}/container/ubuntu-core-12.04.5-core-amd64.tar.gz.root/usr/bin:${PATH};
  fi
- curl -L public-travis-scripts.polysquare.org/python-setup-with-doc.sh | bash
script:
- export MODULE=cmakeast
- curl -L public-travis-scripts.polysquare.org/python-test-module.sh | bash
after_success:
- curl -L public-travis-scripts.polysquare.org/python-coverage.sh | bash
before_deploy:
- source python-prepare-doc-deploy.sh
deploy:
  provider: pypi
  user:
    secure: n+N1B9CiMyHM2SMdkCfRqUk7CIWYA9mtlez7lQW7iCLQNYCvEoZprvUnlvUlKUdafwBWi543Ezes+VTm3cyC9NoTL/NKfFZ4J8ZpBl4JGJJNfnKlXjBsmp2LFCySDVFwft1ed9miIjqkzsYTD2ohyBX+An70yfxMHfQ5DnS3D1Y=
  password:
    secure: i6YvJQnKlOj7kGVUwLn4gL6gYRPoX83IYusz/8GUyA8wz3p3Uiu5jtWwqpu3/U538ESfGFhbaj2bf9VtVbixpk/8+MrGYBVGM+42MB9VpLd6sADe0dqoyW2+yIgodeoLNxBKhK8wg0jVmEtSzRQuakSijlpWF+Pj9lit4GEhBcA=
  on:
    repo: polysquare/cmake-ast
    branch: master
