language: python
cache:
  directories:
  - ~/virtualenv
python:
- '2.7'
- '3.4'
- 'pypy'
env:
- CMAKE_VERSION="3.1"
- CMAKE_VERSION="2.8"
install:
- if [ ${CMAKE_VERSION} == "3.1" ]; then
     sudo apt-get -y purge cmake;
     sudo add-apt-repository -y ppa:kubuntu-ppa/beta;
     sudo apt-get update;
     sudo apt-get install cmake;
  fi
- wget public-travis-scripts.polysquare.org/python-install.sh
- wget public-travis-scripts.polysquare.org/python-lint.sh
- wget public-travis-scripts.polysquare.org/python-tests.sh
- wget public-travis-scripts.polysquare.org/python-coverage.sh
- wget public-travis-scripts.polysquare.org/project-lint.sh
- bash python-install.sh
script:
- bash project-lint.sh -d . -e py
- bash python-lint.sh -m cmakeast
- bash python-tests.sh -m cmakeast
after_success:
- bash python-coverage.sh
after_success:
- coverage report -m
- coveralls
- rm -rf cmakeast.egg-info/
- rm -rf build/
deploy:
  provider: pypi
  user:
    secure: n+N1B9CiMyHM2SMdkCfRqUk7CIWYA9mtlez7lQW7iCLQNYCvEoZprvUnlvUlKUdafwBWi543Ezes+VTm3cyC9NoTL/NKfFZ4J8ZpBl4JGJJNfnKlXjBsmp2LFCySDVFwft1ed9miIjqkzsYTD2ohyBX+An70yfxMHfQ5DnS3D1Y=
  password:
    secure: i6YvJQnKlOj7kGVUwLn4gL6gYRPoX83IYusz/8GUyA8wz3p3Uiu5jtWwqpu3/U538ESfGFhbaj2bf9VtVbixpk/8+MrGYBVGM+42MB9VpLd6sADe0dqoyW2+yIgodeoLNxBKhK8wg0jVmEtSzRQuakSijlpWF+Pj9lit4GEhBcA=
  on:
    repo: polysquare/cmake-ast
    branch: master
